[package]
name = "zksync-os-integration-tests-runner"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
zksync_os_integration_tests = { path = "zksync-os-server/integration-tests" }

anyhow = "1"
test-log = { version = "0.2.18", default-features = false }
tokio = "1.45.1"
alloy = "1.5.2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1.0"
